/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "PrISM_1.h"
#include "PrISM_Clock.h"
#include "RED.h"
#include "RED_aliases.h"
#include "GREEN.h"
#include "GREEN_aliases.h"
#include "BLUE.h"
#include "BLUE_aliases.h"
#include "PrISM_2.h"
#include "isr_WDT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Pin_Mic_D.h"
#include "Pin_Mic_D_aliases.h"
#include "Pin_DLed.h"
#include "Pin_DLed_aliases.h"
#include "Pin_Mic_A.h"
#include "Pin_Mic_A_aliases.h"
#include "ADC_MIC.h"
#include "PWM_Brightness.h"
#include "Pin_ALed.h"
#include "Pin_ALed_aliases.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "Timer_Claps.h"
#include "isr_timer.h"
#include "Pin_Timer_Clear.h"
#include "Pin_Timer_Clear_aliases.h"
#include "isr_complete.h"
#include "BLE_bless_isr.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_MIC_IRQ.h"
#include "ADC_MIC_intClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

